apiVersion: v1
baseDomain: cloud.com
compute:
- hyperthreading: Enabled   
  name: worker
  replicas: 0 
controlPlane:
  hyperthreading: Enabled   
  name: master 
  replicas: 3
metadata:
  name: ocp4
networking:
  clusterNetwork:
  - cidr: 10.128.0.0/14 
    hostPrefix: 23 
  networkType: OpenShiftSDN
  serviceNetwork: 
  - 172.30.0.0/16
platform:
  none: {} 
fips: false
pullSecret: '{"auths":{"bastion.ocp4.cloud.com:5000":{"auth":"YWRtaW46cmVkaGF0"},"cloud.openshift.com":{"auth":"b3BlbnNoaWZ0LXJlbGVhc2UtZGV2K29wZW5zaGlmdDAxcGVudGFsaW5rY29rcjFtdTFiaGlsaGVoaGJycnZpOXBrNHI2cm04azpMRzVRSDdPRFZLVElaS1JPVllQRzlVV1A1RlM4U1YzUkE2MVY2TFJENlRMREI2TkpERzVWVkJHTzI1TzFHUTBO"},"quay.io":{"auth":"b3BlbnNoaWZ0LXJlbGVhc2UtZGV2K29wZW5zaGlmdDAxcGVudGFsaW5rY29rcjFtdTFiaGlsaGVoaGJycnZpOXBrNHI2cm04azpMRzVRSDdPRFZLVElaS1JPVllQRzlVV1A1RlM4U1YzUkE2MVY2TFJENlRMREI2TkpERzVWVkJHTzI1TzFHUTBO"},"registry.connect.redhat.com":{"auth":"NTEwMTUxMTJ8dWhjLTFNdTFCSElMSEVISGJyclZJOXBrNHI2Um04SzpleUpoYkdjaU9pSlNVelV4TWlKOS5leUp6ZFdJaU9pSXdNakF5WldNek56WmxZalkwTkdWaE9XUmxOVE5tWlRVeE5tSmhORGxoWXlKOS5nWi1ZMkNwYktLWk55M0NfMXhDelBFdmdvUmpha0lGMFpNVm5RcDFpTTRyT0o0VHFGcGd0RXVKbVJfREk0X3RrMVFsWlNwZG1lRHd2RWw0elozV1g3TjVGQzAyTVpWVW1lQ1E3YnJaZVFmdGtyZzJMbjVlcGRidlFHejQwazdfUG1UM0MwRFRGZWg0R0UwOG5xTjNBQ0RNMXpiU1Nma2F2bUV5aGVzZmpHRDgtRTFkQWFOcFlCNFNPX2xkR2ZwbWtGOHM1RlBfck1jeFpGOEJ5bF8zUGd1UzRTS2RleHV4S1NrNDM3aTJLckoxTkJLSDNsX0FNLUpSOTk2blZCdjNnSFVBV3RyRDhQekFNUmNVOUp5aUF4dndvcmdHVGNDeHJXT2h4dF9XM1c1QnIyUHZGY2FtOTJ5dmpVTlZ1WG5vMGQzamxBYlFhdERMbnBudDQ0RXJKdjJheHVGZXMtTWo3YzZrWXE1WFpPdkZ3aTAzdEtPdlpyQVpzblpaMnVhRlA2UFRaY240WFU3Y0JPd0xQMmhzT2p2X1Q2bEZBUDNDelh2UjhZUHdJb1hXUVRORFE3aU9XVENUM0twWmJtMFJ5TmVBa25PaGw0MGh1MGNhYzY2d0VneENkX2FqdzRlNXpYOEZSV2p4ODZ0RjFyWUU0ZjlqakJRYkVwa1V6cnFjaVo3RldSRFR3YVhrcC15T3NRejYzaW5pb1AzUDEyVXgtVFNFdjVmSTk0RVZSRUxza2NvQkhqX3VBcTdEdUppdVNuaE4tRUZ4dDJuTjVIeE1pamg4cXBTT0doRmFDRFl0VElqVm5NUkVQZ3dWdm5OQnN4VDI3SHZXOUJORmF5OFhFSXA4VUdSazljc3FtVm1RcDRqSmJVNW9NMEFfZnkzM29wMmxWTUR6aGcxTQ=="},"registry.redhat.io":{"auth":"NTEwMTUxMTJ8dWhjLTFNdTFCSElMSEVISGJyclZJOXBrNHI2Um04SzpleUpoYkdjaU9pSlNVelV4TWlKOS5leUp6ZFdJaU9pSXdNakF5WldNek56WmxZalkwTkdWaE9XUmxOVE5tWlRVeE5tSmhORGxoWXlKOS5nWi1ZMkNwYktLWk55M0NfMXhDelBFdmdvUmpha0lGMFpNVm5RcDFpTTRyT0o0VHFGcGd0RXVKbVJfREk0X3RrMVFsWlNwZG1lRHd2RWw0elozV1g3TjVGQzAyTVpWVW1lQ1E3YnJaZVFmdGtyZzJMbjVlcGRidlFHejQwazdfUG1UM0MwRFRGZWg0R0UwOG5xTjNBQ0RNMXpiU1Nma2F2bUV5aGVzZmpHRDgtRTFkQWFOcFlCNFNPX2xkR2ZwbWtGOHM1RlBfck1jeFpGOEJ5bF8zUGd1UzRTS2RleHV4S1NrNDM3aTJLckoxTkJLSDNsX0FNLUpSOTk2blZCdjNnSFVBV3RyRDhQekFNUmNVOUp5aUF4dndvcmdHVGNDeHJXT2h4dF9XM1c1QnIyUHZGY2FtOTJ5dmpVTlZ1WG5vMGQzamxBYlFhdERMbnBudDQ0RXJKdjJheHVGZXMtTWo3YzZrWXE1WFpPdkZ3aTAzdEtPdlpyQVpzblpaMnVhRlA2UFRaY240WFU3Y0JPd0xQMmhzT2p2X1Q2bEZBUDNDelh2UjhZUHdJb1hXUVRORFE3aU9XVENUM0twWmJtMFJ5TmVBa25PaGw0MGh1MGNhYzY2d0VneENkX2FqdzRlNXpYOEZSV2p4ODZ0RjFyWUU0ZjlqakJRYkVwa1V6cnFjaVo3RldSRFR3YVhrcC15T3NRejYzaW5pb1AzUDEyVXgtVFNFdjVmSTk0RVZSRUxza2NvQkhqX3VBcTdEdUppdVNuaE4tRUZ4dDJuTjVIeE1pamg4cXBTT0doRmFDRFl0VElqVm5NUkVQZ3dWdm5OQnN4VDI3SHZXOUJORmF5OFhFSXA4VUdSazljc3FtVm1RcDRqSmJVNW9NMEFfZnkzM29wMmxWTUR6aGcxTQ=="}}}'
sshKey: 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDU1lGzL5efvWmG1WFvFcrlu2WcVuNJuUwqCMYBlVWpgHZHyikkVrDfpQXGOFw1Py2HMrUss8n/OLy3DUgYQFCdAyq7bHdMfLS8vDhStB+LFZlqwseHnSbuWbD9cDbb5qndoMnMomVujZjGjt8XiR5HR/pNWy3tBYY8qhtiueRtc48riwKYfehuPh6lWkVIOiCopzf8W7gonGl4sLCUWOqtnObh8fdIIwmL3i1zbZHZL55eBYjwEGLQLKNK1bDBd2B9glxv8aIJXJ6r5PX66yuJE9iXAlrU3sbcA14Y7xMFKSMBYmKRt/skognM/iILzNrlhz/XYD/IgZz100Ti0GFzaCZrVMWpcEqkmmevmaaZl5b8QgjU4okOuMMtjSLH/CMyXSUcAxd2XBRYByJc+y9rGP346QxTU0cMqkevQ7oRl9ixZoWN6QgeKMnhuChmqw627KKiMNqPT7CDa2GSBx1vkVJJ9gWavqebqR+YzNEVaNPAgvFo8+XjllXDx2ONWI/MEV1u3q6aa2jbBtQFvqLZHFHy8MVHOrQ/v5aktKj+OyR8rqPDA6+hSu+913vAjT42hNMgfuicrVNy5JStdDyCogf+xtr72CpeX44l/0ZrptXjOidgmZuueTdx4P/n+OnIRJ8eTJNZ8jnfnkIU7yY3HVOFmC7igvEuUAEL8xpFuQ== root@bastion.ocp4.cloud.com'
additionalTrustBundle: |
  -----BEGIN CERTIFICATE-----
  MIIFmTCCA4GgAwIBAgIJAMrPYsQMPk4rMA0GCSqGSIb3DQEBCwUAMGMxCzAJBgNV
  BAYTAktSMRUwEwYDVQQHDAxEZWZhdWx0IENpdHkxHDAaBgNVBAoME0RlZmF1bHQg
  Q29tcGFueSBMdGQxHzAdBgNVBAMMFmJhc3Rpb24ub2NwNC5jbG91ZC5jb20wHhcN
  MjAwNzI4MDg1MTA0WhcNMzAwNzI2MDg1MTA0WjBjMQswCQYDVQQGEwJLUjEVMBMG
  A1UEBwwMRGVmYXVsdCBDaXR5MRwwGgYDVQQKDBNEZWZhdWx0IENvbXBhbnkgTHRk
  MR8wHQYDVQQDDBZiYXN0aW9uLm9jcDQuY2xvdWQuY29tMIICIjANBgkqhkiG9w0B
  AQEFAAOCAg8AMIICCgKCAgEAqckobXzxspnRDr4ZiLCOCi0rFnfI9mdVi3HXYAuN
  pvHrLlMAazgc7X8stQseLpogo6S3psabodnKFKfbNwt1K+NChW4HYoV0Ocp2/sw0
  yPgOAj2R0Y5HqyokDEQtYnUhk8g3+vJXrL+Co8uprCJ3/4FQ/TGeNgqN4hCBkVQQ
  BAONPisXrszEY+sW2d8+bkCC+qd9elsiZgA86Zwi2ZrPNew+/Ea2kUFbC9OYzolP
  /+0IC7EsMIyvrKlJje6sGPB1SrB/zD9JZIUich6pEjytBCNITGmj+jDAtbaQSayE
  Vqz2IZ7tHJ1e+/WAwpZuzA2R8pjjry3IKLESw7k+7qPryjpZfIcii51S+qYQbplU
  7vnnNYomP5DwU9BtdxxCfSs3E8N5l7PzNFlfooi7BkSFvB6HWyG/tIGqsQInHIk6
  yHN6IwfQ0J6NzAe/T8wHP66MwTIvI/o+N9ehKz2RxR2nFv8mbd9hQ6esxE2mefVT
  HHh60w+0Fm5kDne56f0utg58DRueJX7qa6OT48tdXQxZtt9mxvd6imyM5ETrPCl1
  tMuU7T2sl9Gste3Lc2O8hOQGBYzppR9n91WCiNeUIPmrzVaswBGjCkTWgz/Uvvh1
  gmlJmqc++MgSPvEaZekJy141UAa2V5WNfFy1xfKE/38IhqRUIQ/+0MYgrvagmPGu
  2AcCAwEAAaNQME4wHQYDVR0OBBYEFBNWExfuAxxC94xH0rxdp2H+N9sCMB8GA1Ud
  IwQYMBaAFBNWExfuAxxC94xH0rxdp2H+N9sCMAwGA1UdEwQFMAMBAf8wDQYJKoZI
  hvcNAQELBQADggIBAHORqHJ9BXeoGgP/7aIcLKDHKJwyBTetIWeoLxAb6cB5R1+v
  XKEvGUbSr/N5ANqfPNjgSuAp5FzAANoDLcxyhVT4A3JVEKNWCyKZIUpxrBdEmUUo
  7rv/32nWH27x4wFe7DuRPT0GNE1iZDrWjPBXmWF2iJjqtQexu8GsEKj8ndFx6TiP
  TwBfvuqLtQoN8X8elGznZ8KEJ1vMDp9J0/7nCrp0gAhzNHaJCBg3dl2SQ0um7bdy
  qzsOTykFJSbj6H+2J1m/N/LcEFCg3fLUtY6SFQb/nKOKDvv7KnlzDqD3Oi7eYfoR
  G/cfDQ+ElgGbvqFsGe/axDEhJQjFHzrS041wjYVMBY7o1Iz2hyF9Cr/3zGiSDyvP
  /yMdlwRmhxODQQw2lkeuil54H8j/k+aa4HDGd1B6oSNzQkOXJPQUKHtGhgwpKb+1
  kVE85AGqLM1B2M7H/X6OEa1q+udX4JpdYOWt7Opy+T9D0Gy62Fe1zi3YNk+PKuED
  btsltYxnTbCzbBGFZnPTnttK4N6QiLvlFGl8EfL7k3VWs0KdwbjAKKCsoTFhw3sW
  m85BXJVaSnKc79eD399VkKWxyUdQsEYfCo7ufzfWn694p/mU/e/yQVVGik9/Nl9O
  SnsJGth+wDJNa7WJiNCaXhbcRYI7moM/zP+OPLBhEB738uH31WmDZYR2HbbC
  -----END CERTIFICATE-----
imageContentSources:
- mirrors:
  - bastion.ocp4.cloud.com:5000/ocp4/openshift4
  source: quay.io/openshift-release-dev/ocp-release
- mirrors:
  - bastion.ocp4.cloud.com:5000/ocp4/openshift4
  source: quay.io/openshift-release-dev/ocp-v4.0-art-dev
